name: continuous-delivery
on:
  push:
    branches: [main]
jobs:
  continuous-delivery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.CICD_GITHUB_REPOSITORY_TOKEN }}

      - uses: ohpensource/generate-version-and-release-notes-gh-action@v1.0.1
        name: semver & changelog
        with:
          user-name: "GitHub Actions"
          user-email: "github-svc@ohpen.com"
          skip-git-commit: "false"
          version-prefix: "v"
          settings-file: repo-config.json
